### ISSUE TITLE
TypeError occurring 

### ISSUE THREAD

**Issue by subtra3t** [davidcallanan/py-myopl-code#14]
So, I just finished with the code for the first video. I have made a lot of changes in the code, so my code may seem to be different than yours. The following error is raised:

```python
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    tokens, error = lexer.make_tokens()
  File "main.py", line 65, in make_tokens
    tokens.append(self.make_number())
  File "main.py", line 88, in make_number
    self.advance()
  File "main.py", line 54, in advance
    if self.character in " \t":
TypeError: 'in <string>' requires string as left operand, not NoneType
```

And my code is the following:
```python
operators = {
    "+" : "ADDITION",
    "-" : "SUBTRACTION",
    "*" : "MULTIPLICATION",
    "/" : "DIVISION",
    "(" : "PARENTHESIS_LEFT",
    ")" : "PARENTHESIS_RIGHT"
}

class Exception:
    def __init__(self, name, details, inp):
        self.name = name + "Error"
        self.details = details.format(inp=inp)

    def __repr__(self):
        return f"{self.name}: {self.details}"


class InvalidCharacter(Exception):
    def __init__(self, character):
        super().__init__("InvalidCharacter", "\"{inp}\" is not a valid number, integer or decimal", character)

class Token:
    def __init__(self, type_of, value):
        self.type_of = type_of
        self.value = value
    
    def __repr__(self):
        if (self.value != "") and (self.type_of != ""): 
            return "{type_of} :: {value}".format(
                type_of = self.type_of,
                value = self.value
            )

        else:
            return self.type_of


class Lexer:
    def __init__(self, text):
        self.text = text
        self.position = -1
        self.character = None
        self.advance()
    
    def advance(self):
        self.position += 1

        if self.position < len(self.text):
            self.character = self.text[self.position]
        else:
            self.character = None
        
        if self.character in " \t":
            self.advance()
    
    def make_tokens(self):
        tokens = []

        while self.character != None:
            if self.character in "+-*/()":
                tokens.append(Token("OPERATOR", operators[self.character]))
                self.advance()
            elif self.character in "0123456789":
                tokens.append(self.make_number())
                self.advance()
            else:
                self.advance()
                return ([], InvalidCharacter(self.character))

        return (tokens, None)

    def make_number(self):
        num_string = ""
        dot_count = 0

        while self.character != None:
            if self.character in "0123456789.":
                if self.character == ".":
                    if dot_count > 0:
                        break
                    
                    dot_count += 1
                    num_string += "."
                else:
                    num_string += self.character

                self.advance()
            elif self.character in " \t":
                self.advance()
            self.advance()
        

        if dot_count == 0:
            return Token("INTEGER", int(num_string))
        elif dot_count == 1:
            return Token("DECIMAL", float(num_string))
        else:
            return "Something went very wrong. Here is your number: " + num_string

            


def zero_pad(n, width):
    out = str(n)

    while len(out) < width:
        out = "0" + out

    return out

def array_pad(arr):
    out = ""
    
    if not(arr):
        return None

    out += "["

    for el in arr:
        out += "\n\t" + el + ","
    
    out += "\n]"

    return out


n = 1
while True:
    inp = input(f"[{zero_pad(n, 3)}] >>> ")
    n += 1

    lexer = Lexer(inp)

    tokens, error = lexer.make_tokens()

    if error:
        print(repr(error))
    else:
        print(array_pad(tokens))
```

I know that I probably appear as some kind of snob to you, but I would really appreciate it anyone bothered to help me out.

**Comment by subtra3t** [comment]
**CODE UPDATE**: I managed to fix the errors, and now everything seems to working fine. But the lexer seems to be only registering the first token.

**Comment by Roshiago** [comment]
Hi @subtra3t, i can get a fix for you
It seems, that space and tab character need check in Lexer.make_tokens.
If you wanna check space and tab character in advance method you should check for None. Thats because advance becomes recursive.
For example: 
"1 + 2"
Characters: '1', ' ', '+', ' ', '2'
Parse manualy:
1. character = '1' -> its number, than make_number
2. in make_number we are use advance function that might be recursive
3. after '1' character -> ' ' character
And in this situation you just skip it in advance method because advance call advance one more time and next character becomes '+', not ' '

This is fix code
```
operators = {
    "+" : "ADDITION",
    "-" : "SUBTRACTION",
    "*" : "MULTIPLICATION",
    "/" : "DIVISION",
    "(" : "PARENTHESIS_LEFT",
    ")" : "PARENTHESIS_RIGHT"
}

class Exception:
    def __init__(self, name, details, inp):
        self.name = name + "Error"
        self.details = details.format(inp=inp)

    def __repr__(self):
        return f"{self.name}: {self.details}"


class InvalidCharacter(Exception):
    def __init__(self, character):
        super().__init__("InvalidCharacter", "\"{inp}\" is not a valid number, integer or decimal", character)

class Token:
    def __init__(self, type_of, value):
        self.type_of = type_of
        self.value = value
    
    def __repr__(self):
        if (self.value != "") and (self.type_of != ""): 
            return "{type_of} :: {value}".format(
                type_of = self.type_of,
                value = self.value
            )

        else:
            return self.type_of
    
    def __str__(self):
        return self.__repr__()


class Lexer:
    def __init__(self, text):
        self.text = text
        self.position = -1
        self.character = None
        self.advance()
    
    def advance(self):
        self.position += 1

        if self.position < len(self.text):
            self.character = self.text[self.position]
        else:
            self.character = None
        
        if self.character != None and self.character in " \t":
            self.advance()
    
    def make_tokens(self):
        tokens = []

        while self.character != None:
            if self.character in "+-*/()":
                tokens.append(Token("OPERATOR", operators[self.character]))
                self.advance()
            elif self.character in "0123456789":
                tokens.append(self.make_number())
            else:
                self.advance()
                return ([], InvalidCharacter(self.character))

        return (tokens, None)

    def make_number(self):
        num_string = ""
        dot_count = 0

        while self.character != None and self.character in "0123456789.":
            if self.character == ".":
                if dot_count > 0:
                    break
                
                dot_count += 1
                num_string += "."
            else:
                num_string += self.character

            self.advance()
        

        if dot_count == 0:
            return Token("INTEGER", int(num_string))
        elif dot_count == 1:
            return Token("DECIMAL", float(num_string))
        else:
            return "Something went very wrong. Here is your number: " + num_string

            


def zero_pad(n, width):
    out = str(n)

    while len(out) < width:
        out = "0" + out

    return out

def array_pad(arr):
    if not(arr):
        return None

    arr_str = ',\n\t'.join(map(str, arr))
    out = f"[\n\t{arr_str}\n]"
    
    return out


n = 1
while True:
    inp = input(f"[{zero_pad(n, 3)}] >>> ")
    n += 1

    lexer = Lexer(inp)

    tokens, error = lexer.make_tokens()

    if error:
        print(repr(error))
    else:
        print(array_pad(tokens))
```
I made some improve code for array_pad, but its not necessary

**Comment by subtra3t** [comment]
@Roshiago Thanks!
